#!/usr/bin/env bash
# run-drill.sh -- orchestrate a full injected-incident drill against a live kind
# cluster, with timestamps, and write a real incident timeline to
# LIVE-INCIDENT-EVIDENCE.txt. This is the heavy, multi-minute live drive, so it
# is GATED behind RUN_LIVE=1 (keeps validate.sh fast by default).
#
#   inject  -> observe (capture DEGRADED symptom) -> recover -> observe (HEALTHY)
#
# It ALWAYS deletes ns/lab-incident on exit (success, failure, or Ctrl-C) so the
# shared cluster is left clean. It only ever touches ns/lab-incident.
#
# Usage:
#   RUN_LIVE=1 ./run-drill.sh
#   RUN_LIVE=1 KEEP_NS=1 ./run-drill.sh     # keep the namespace for inspection
#
# Output:
#   LIVE-INCIDENT-EVIDENCE.txt   (committed evidence: the actual drill timeline)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$HERE/lib.sh"

if [ "${RUN_LIVE:-0}" != "1" ]; then
  cat >&2 <<'EOF'
run-drill.sh is a live, multi-minute drive against a real cluster and is gated.
Re-run with RUN_LIVE=1 to execute it:

    RUN_LIVE=1 ./run-drill.sh

It deploys to ns/lab-incident, injects a readiness-probe fault, captures the
symptom, rolls back, confirms recovery, writes LIVE-INCIDENT-EVIDENCE.txt, and
deletes the namespace.
EOF
  exit 2
fi

require_cluster || exit 1

EVIDENCE="${EVIDENCE:-$HERE/LIVE-INCIDENT-EVIDENCE.txt}"
export EVIDENCE
: >"$EVIDENCE"   # truncate; this run becomes the committed evidence.

# cleanup runs via the EXIT/INT/TERM trap below; shellcheck cannot see that
# indirect invocation, so its body looks "unreachable" (SC2317) -- silence it.
# shellcheck disable=SC2317
cleanup() {
  local rc=$?
  if [ "${KEEP_NS:-0}" = "1" ]; then
    log "CLEANUP: KEEP_NS=1 -- leaving ns/$NS in place for inspection"
  else
    log "CLEANUP: deleting ns/$NS (leave nothing running on the shared cluster)"
    k delete ns "$NS" --wait=true --ignore-not-found >/dev/null 2>&1 || true
    log "CLEANUP: ns/$NS deleted"
  fi
  log "DRILL: finished (overall exit=$rc)"
  exit "$rc"
}
trap cleanup EXIT INT TERM

{
  echo "############################################################"
  echo "#  INJECTED-INCIDENT DRILL -- payments-web readiness fail   #"
  echo "#  Cluster context: ${KUBE_CONTEXT:-$(kubectl config current-context 2>/dev/null)}"
  echo "#  Namespace      : $NS"
  echo "#  Generated by   : run-drill.sh (RUN_LIVE=1)"
  echo "############################################################"
} >>"$EVIDENCE"

log "DRILL: ===== PHASE 1: INJECT (deploy healthy, then ship the bad v2) ====="
"$HERE/inject.sh"

# Give the bad rollout a few seconds to tear down old pods and empty endpoints.
log "DRILL: allowing the fault to take effect (readiness probes failing)..."
for _ in $(seq 1 20); do
  [ "$(ready_endpoints)" -eq 0 ] && break
  sleep 2
done

log "DRILL: ===== PHASE 2: OBSERVE (capture the degraded symptom) ====="
DETECTED=1
if "$HERE/observe.sh"; then
  # observe.sh exits 0 only if it saw a HEALTHY state -> the fault did not bite.
  DETECTED=0
fi
if [ "$DETECTED" -eq 1 ]; then
  log "DRILL: DETECTION CONFIRMED -- the injected fault produced an observable outage"
else
  log "DRILL: WARNING -- expected a degraded state but observed healthy; failing the drill"
fi

log "DRILL: ===== PHASE 3: RECOVER (rollback + restore safe strategy) ====="
RECOVERED=0
if "$HERE/recover.sh"; then
  RECOVERED=1
fi

log "DRILL: ===== PHASE 4: VERIFY (confirm the service is healthy again) ====="
VERIFIED=0
if "$HERE/observe.sh" --expect-healthy; then
  VERIFIED=1
fi

# ---- overall verdict ----------------------------------------------------------
echo "" >>"$EVIDENCE"
if [ "$DETECTED" -eq 1 ] && [ "$RECOVERED" -eq 1 ] && [ "$VERIFIED" -eq 1 ]; then
  log "DRILL: RESULT = PASS (fault injected -> detected -> recovered -> verified healthy)"
  RESULT_RC=0
else
  log "DRILL: RESULT = FAIL (detected=$DETECTED recovered=$RECOVERED verified=$VERIFIED)"
  RESULT_RC=1
fi

log "DRILL: incident timeline written to $EVIDENCE"
# cleanup() runs via the EXIT trap and preserves this exit code.
exit "$RESULT_RC"
