#!/usr/bin/env bash
#
# drill.sh — end-to-end golden-path demonstration, with captured evidence.
#
# Proves the paved road works by DRIVING it: scaffold a fresh service, build its
# image, run the container, curl its endpoints, deploy the rendered chart to the
# live kind cluster in a unique namespace, helm-test it, then tear everything
# down. Real output is appended to docs/evidence/drill-output.txt (committed).
#
# This is a multi-minute live drive (docker build + cluster round-trips), so it
# is gated behind RUN_LIVE=1 and NOT part of the fast validate.sh.
#
# Usage:
#   RUN_LIVE=1 ./drill.sh                       # full drive incl. cluster
#   RUN_LIVE=1 SKIP_K8S=1 ./drill.sh            # scaffold+build+run only
#
# Env:
#   RUN_LIVE   must be 1 or the script refuses to run (prints how to enable).
#   SKIP_K8S   if 1, skip the kind-cluster deploy/helm-test stage.
#   KCONTEXT   kube context (default kind-course).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KCONTEXT="${KCONTEXT:-kind-course}"
EVIDENCE_DIR="$HERE/docs/evidence"
EVIDENCE="$EVIDENCE_DIR/drill-output.txt"

if [[ "${RUN_LIVE:-0}" != "1" ]]; then
  echo "drill.sh is a live, multi-minute drive. Re-run with:"
  echo "    RUN_LIVE=1 ./drill.sh"
  exit 0
fi

mkdir -p "$EVIDENCE_DIR"

# A unique workspace + names so concurrent/repeated runs never collide and we
# never touch another namespace.
RUN_ID="drill-$(date +%Y%m%d-%H%M%S)-$$"
WORK="$(mktemp -d)"
SVC="drillsvc"
IMG="pgp-drill:${RUN_ID}"
NS="pgp-${RUN_ID}"
CID=""

log() { printf '\n=== %s ===\n' "$*"; }

cleanup() {
  set +e
  [[ -n "$CID" ]] && docker rm -f "$CID" >/dev/null 2>&1
  docker rmi "$IMG" >/dev/null 2>&1
  if [[ "${SKIP_K8S:-0}" != "1" ]]; then
    kubectl --context "$KCONTEXT" delete ns "$NS" --wait=false >/dev/null 2>&1
  fi
  rm -rf "$WORK"
  echo "[cleanup] removed image, container, namespace $NS, and $WORK"
}
trap cleanup EXIT

# Tee everything to the evidence file (fresh each run).
exec > >(tee "$EVIDENCE") 2>&1

cat <<HDR
################################################################################
# platform-golden-path DRILL — captured $(date -u +%Y-%m-%dT%H:%M:%SZ)
# run id: $RUN_ID
# This file is generated by drill.sh (RUN_LIVE=1) and committed as evidence.
################################################################################
HDR

log "tool versions"
docker --version
helm version --short
kubectl version --client 2>/dev/null | head -1 || true
kubeconform -v
python3 --version

log "1. scaffold a fresh service: $SVC"
"$HERE/solution/scaffold.sh" "$SVC" "$WORK/$SVC"
# Defensive: a clean tree listing (no bytecode from any prior step).
find "$WORK/$SVC" -name __pycache__ -type d -prune -exec rm -rf {} + 2>/dev/null || true
echo "--- generated tree ---"
find "$WORK/$SVC" -type f | sort | sed "s#$WORK/##"
echo "--- no placeholders should remain ---"
if grep -rIl '__SERVICE_NAME__' "$WORK/$SVC"; then
  echo "FAIL: placeholder leaked"; exit 1
else
  echo "OK: zero placeholders in generated service"
fi

log "2. unit tests of the generated service"
( cd "$WORK/$SVC" && python3 -m unittest discover -s tests -p 'test_*.py' 2>&1 | tail -5 )
# Drop the bytecode the test run just produced so the evidence/tree stays clean.
find "$WORK/$SVC" -name __pycache__ -type d -prune -exec rm -rf {} + 2>/dev/null || true

log "3. docker build the generated service"
docker build -t "$IMG" "$WORK/$SVC" 2>&1 | tail -6
echo "--- image size ---"
docker images "$IMG" --format '{{.Repository}}:{{.Tag}}  {{.Size}}'

log "4. run the container and probe it"
CID="$(docker run -d -p 0:8080 "$IMG")"
sleep 2
PORT="$(docker port "$CID" 8080/tcp | head -1 | sed 's/.*://')"
echo "container $CID on host port $PORT"
echo "GET /healthz -> $(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/healthz")  body: $(curl -s "http://127.0.0.1:$PORT/healthz")"
echo "GET /readyz  -> $(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/readyz")  body: $(curl -s "http://127.0.0.1:$PORT/readyz")"
echo "GET /        -> body: $(curl -s "http://127.0.0.1:$PORT/")"
echo "--- container runs as (must be non-root uid 10001) ---"
docker exec "$CID" id

if [[ "${SKIP_K8S:-0}" == "1" ]]; then
  log "SKIP_K8S=1 — skipping cluster stage"
  echo "DRILL COMPLETE (no-k8s)"
  exit 0
fi

log "5. load image into kind and deploy the chart to a unique namespace"
kind load docker-image "$IMG" --name "${KCONTEXT#kind-}" 2>&1 | tail -2
kubectl --context "$KCONTEXT" create ns "$NS"
helm --kube-context "$KCONTEXT" install "$SVC" "$WORK/$SVC/chart" \
  --namespace "$NS" \
  --set image.repository="pgp-drill" \
  --set image.tag="${RUN_ID}" \
  --set image.pullPolicy=Never \
  --wait --timeout 90s
echo "--- rollout status ---"
kubectl --context "$KCONTEXT" -n "$NS" rollout status deploy/"$SVC" --timeout=60s
echo "--- pods (note READY + non-root) ---"
kubectl --context "$KCONTEXT" -n "$NS" get pods -o wide
echo "--- effective securityContext on the running pod ---"
kubectl --context "$KCONTEXT" -n "$NS" get pod -l app.kubernetes.io/name="$SVC" \
  -o jsonpath='{.items[0].spec.containers[0].securityContext}' ; echo

log "6. helm test (in-cluster /healthz smoke)"
# `helm test` exits non-zero (and set -e aborts) if the test pod fails, so a
# clean exit here IS the pass. We also print the test pod's phase explicitly.
helm --kube-context "$KCONTEXT" test "$SVC" --namespace "$NS" 2>&1 \
  | grep -E 'Phase|TEST SUITE|Error|succeeded|failed' || true
echo "--- test pod phase ---"
kubectl --context "$KCONTEXT" -n "$NS" get pod "${SVC}-test-connection" \
  -o jsonpath='{.status.phase}' 2>/dev/null; echo
echo "helm test exited 0 => the in-cluster /healthz probe returned 200"

log "DRILL COMPLETE — all stages passed"
